Feature 34 page options properties
Metatavu/oss-surveys-api pull request #35
Opened 2023-05-16 10:51 UTC by kaeline

https://github.com/Metatavu/oss-surveys-api/issues/34

2023-05-16 12:43 UTC, anttileppa requested changes

2023-05-16 12:43 UTC, anttileppa commented on src/main/resources/db/changeLog.xml
> +            </column>
Remove this

2023-05-16 12:47 UTC, kaeline commented on src/main/kotlin/fi/metatavu/oss/api/impl/pages/questions/PageQuestionController.kt
> +            return
But it's not an error, is it? Questions are optional after all, it's just that no work is required if there was no question on the page and no new question if being created.

2023-05-16 12:54 UTC, kaeline commented on src/main/kotlin/fi/metatavu/oss/api/impl/pages/questions/PageQuestionController.kt
> +                return
If it an error, then I think I should not limit it just to updating the options. I will make all changes to published questions 400.

2023-05-17 08:51 UTC, anttileppa approved these changes

2023-05-17 08:51 UTC, merged